# This is a basic workflow that is manually triggered

name: Shell commands

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:[push]

jobs:
  # This workflow contains a single job called "greet"
  run-shell-command:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello World"
